name: yaml_to_string
description: |-
  [yaml_to_string]
  fork of the yaml_writer package for better null handling
version: 2025.502.1742
homepage: 
repository: https://github.com/dart-pkg/yaml_to_string
environment:
  sdk: ^3.7.2
dev_dependencies:
  test: ^1.26.2
  output: ^2025.502.1958
  lints: ^6.0.0
